### ISSUE TITLE
how to change color

### ISSUE THREAD

**Issue by xxholly32** [tolking/vuepress-theme-default-prefers-color-scheme#1]
hi

I don't understand how your project went dark 

ty  😄

**Comment by tolking** [comment]
[prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme)
- Mojave 10.14 or windows 10 1809
- [browsers](https://caniuse.com/#search=prefers-color-scheme)

up to 1.0.1 then you can change the `defaultTheme`

**Comment by xxholly32** [comment]
ok I see you've made some changes，I really like your ideas and ououe 

> ps: i don know what ououe means

ty for you time 😄
