### ISSUE TITLE
Add support for PWA popup

### ISSUE THREAD

**Issue by ekarad1um** [tolking/vuepress-theme-default-prefers-color-scheme#12]
The dark scheme seems not covered on PWA popup, just have a fix? Thanks.
Ref: https://vuepress.vuejs.org/plugin/official/plugin-pwa.html#customize-the-ui-of-sw-update-popup

**Comment by ekarad1um** [comment]
![A958DD40-C571-43CA-83F8-A7682B7F83C3](https://user-images.githubusercontent.com/15633984/76345028-9314f300-633d-11ea-8aaf-f9849d859abd.jpeg)

**Comment by tolking** [comment]
You can try v1.0.6. The styles take effect after the second build

**Comment by ekarad1um** [comment]
> You can try v1.0.6. The styles take effect after the second build

Solved, thanks! Anyway, correct color with customized button style may looks better.
![9809E296-7773-4566-959A-AF4874C565D9](https://user-images.githubusercontent.com/15633984/76396593-749e0e80-63b4-11ea-8cc5-ae644b2e5729.jpeg)
