### ISSUE TITLE
Typo in palette.styl

### ISSUE THREAD

**Issue by jrappen** [tolking/vuepress-theme-default-prefers-color-scheme#14]
@tolking I assume the following is a typo:

https://github.com/tolking/vuepress-theme-default-prefers-color-scheme/blob/ab0d64f554bc85c9f45aa71963613680b89ec97f/styles/palette.styl#L3

where `accentColors` should have been `accentColor`. At least that is what all other references point to.

---

Compare:

* https://github.com/tolking/vuepress-theme-default-prefers-color-scheme/search?q=accentColors&unscoped_q=accentColors
* https://github.com/tolking/vuepress-theme-default-prefers-color-scheme/search?q=accentColor&unscoped_q=accentColor

**Comment by tolking** [comment]
you are right

**Comment by jrappen** [comment]
fixed in tolking/vuepress-theme-default-prefers-color-scheme@fa1b010
