### ISSUE TITLE
设置时间段后不正常显示

### ISSUE THREAD

**Issue by xuek9900** [tolking/vuepress-theme-default-prefers-color-scheme#15]
按照文档配置设置 defaultTheme: { light: [6, 18], dark: [18, 6] } 后，时间到达 18 点后去刷新页面黑色主题只一闪而过, [看这里](http://www.xwbuilders.com:9018/soonspacejs/Docs/)

**Comment by tolking** [comment]
请检查看你的配置，是否引用必须的 postcss 插件 (设置 defaultTheme 必须要引用 css-prefers-color-scheme/postcss)
``` js
themeConfig: {
    defaultTheme: { light: [6, 18], dark: [18, 6] }
  },
  postcss: {
    plugins: [
      require('css-prefers-color-scheme/postcss'),
      require('autoprefixer')
    ]
  }
```

**Comment by xuek9900** [comment]
ok，没认真看文档，我的错，谢谢😄！
