### ISSUE TITLE
Missing variables

### ISSUE THREAD

**Issue by jrappen** [tolking/vuepress-theme-default-prefers-color-scheme#17]
Hello @tolking,

could you add some variables (for me) to your theme?

Found these missing while looking at [`@vuepress/core/lib/client/style/config.styl`](https://github.com/vuejs/vuepress/blob/master/packages/%40vuepress/core/lib/client/style/config.styl):

* `$badgeTipColor` (and dark variant)
* `$badgeWarningColor` (and dark variant)
* `$badgeErrorColor` (and dark variant)

Found these missing while testing your theme and looking at [`styles/palette.styl`](https://github.com/tolking/vuepress-theme-default-prefers-color-scheme/blob/master/styles/palette.styl):

* `$tipColor` (and dark variant)
* `$lighten10AccentColor` (and dark variant)
* `$lighten10TextColor` (and dark variant)
* `$lighten20TextColor` (and dark variant)
* `$lighten25TextColor` (and dark variant)
* `$lighten35TextColor` (and dark variant)
* `$lighten40TextColor` (and dark variant)
* `$darken10AccentColor` (and dark variant)
* `$darken10BgColor` (and dark variant)
* `$darken10BorderColor` (and dark variant)

Thanks!

**Comment by tolking** [comment]
add 
- $badgeTipColor
- $badgeWarningColor
- $badgeErrorColor
- $tipColor

about
- $lighten10AccentColor
- $lighten10TextColor
...
I don't think it's necessary to add these variables

modify in this way
``` css
// .vuepress -> styles -> index.styl
:root
  --lighten10AccentColor #ff0000
  --lighten10TextColor #777777
  //...
  @media (prefers-color-scheme dark)
    --lighten10AccentColor #ffff00
    --lighten10TextColor #aaaaaa
    //...
```
