### ISSUE TITLE
v1.1.0 not using preferred scheme in Chrome on Windows

### ISSUE THREAD

**Issue by spawnia** [tolking/vuepress-theme-default-prefers-color-scheme#20]
I tried upgrading to version 1.1.0, but found that it did not respect my preferred color scheme, using Chrome on Windows. Changing the `<html>` tag to contain `theme="dark"` did work, but the "magic" was gone.

Reverting back to 1.0.9 resolved the issue and *it just works* again.

**Comment by tolking** [comment]
You should remove the defaultTheme, The defaultTheme invalidates the prefers-color-scheme

**Comment by spawnia** [comment]
Thanks for the response.

I think that this configuration is misleading, I would not expect the `defaultTheme` to just *set* the theme. My impression was that the entire point of this plugin was to have the theme be dynamic, overruling that through a setting invalidates its usefulness.

On another note: This was a breaking change, assuming you follow semantic versioning it warrants a major version bump.

**Comment by tolking** [comment]
Thanks, I will optimize my docs.

v1.0.9, defaultTheme work with a postcss plugin `css-prefers-color-scheme/postcss`.
v1.1.0, i just use `html[theme=light] html[theme=dark]` replace `css-prefers-color-scheme/postcss`.

**Comment by jrappen** [comment]
Assuming the order of preferences is:

- `defaultTheme`'s default
- overriding `defaultTheme`
- brower preferences

The current behavior as of `v1.1.2` is that overriding `defaultTheme` also overrides the browser preferences contrary to me assuming it should only override the (vuepress core) default light theme (for time slots) not the browser preferences as well.

I also assume @spawnia meant to imply the same above with his comments.

---

@tolking Where and how do I set a "default" dark theme for old browser's not preferring either a light or dark theme? Looking at **the third section of**:

https://caniuse.com/?search=prefers-color-scheme

this seems to be the same issue with @spawnia 's Chrome browser not communicating a default theme on Windows with the current release.

**Comment by tolking** [comment]
@jrappen The `defaultTheme` overrides the  browser preferences, it is true.
It does bring some troubles to use.

---

I have an idea, it is delete `defaultTheme` then add a button to control show `auto` `light` or `dark` theme (It should be a built-in plugIn). Will this be better understood than now

**Comment by jrappen** [comment]
Maybe my request wasn't clear.

I was not asking for a button. I prefer the dynamic nature of the plugin, as does @spawnia. I guess we both are asking for a way to override the vuepress core default theme while following browser preferences if set.

A solution might be a change in the ranking of the individual settings?

**Comment by spawnia** [comment]
The name `defaultColor` is misleading, since it does not change the default but rather overrides any other setting.

I advocate to restore it to its previous behavior of actually functioning as a default. Totally overriding user preference goes exactly against what I want out of this package.

**Comment by tolking** [comment]
I know what you mean. But from the beginning, The defaultTheme overrides the browser preferences, I can't destroy it now. 
If need to control the `themes` when the  prefers-color-scheme not working, I can only add one config now. This may cause more trouble

**Comment by spawnia** [comment]
> But from the beginning, The defaultTheme overrides the browser preferences

That was not the case in 1.0.9, back then the browser preference won over the `defaultTheme`.

**Comment by spawnia** [comment]
How about just adding in a second option called `overrideTheme` to have a way to force a theme and reverting `defaultTheme` to function as the fallback in case the user has no preference?

**Comment by tolking** [comment]
> v1.0.9, defaultTheme work with a postcss plugin css-prefers-color-scheme/postcss.
Adding overrideTheme is possible

**Comment by spawnia** [comment]
Thank you @tolking for addressing this issue and a great v2
