### ISSUE TITLE
Toggle dark mode

### ISSUE THREAD

**Issue by nandi95** [tolking/vuepress-theme-default-prefers-color-scheme#29]
This is a feature request.

Is it planned to add a feature to support toggling the theme? This could also be saved in local storage so the site remebers the user's choice.

**Comment by tolking** [comment]
Adding a toggling button will destroy the default UI, it should be a plugin.
If [vuepress-next](https://github.com/vuepress/vuepress-next/issues/29) support  dark mode, this theme will be moved to a toggling plugin.

Now, you can change it by:
- `<html>` -> auto
- `<html theme="light">` -> light
- `<html theme="dark">` -> dark
