### ISSUE TITLE
something wrong in warning and danger tips

### ISSUE THREAD

**Issue by xxholly32** [tolking/vuepress-theme-default-prefers-color-scheme#3]
[demo](https://xxholly32.github.io/vuepress-plugin-code-box/guide/#%E5%AE%89%E8%A3%85)

cant see the warning words.

and added pr 🤔

**Comment by tolking** [comment]
your defaultTheme is String,  remove "

defaultTheme: { dark: [18, 6] }

**Comment by xxholly32** [comment]
yeah, i know, i fixed it;

this issue was fixd with my pr
