### ISSUE TITLE
Scroll bar

### ISSUE THREAD

**Issue by junaga** [tolking/vuepress-theme-default-prefers-color-scheme#33]
Hi, sorry for bothering.
I just stumbled across your project and included it immediately, really loving it.
However.. I noticed that the scroll bar is being changed by the theme.
The default theme (vuepress 1.8.2) uses the browers vanilla scroll bar.

Can I, somehow change that?
So it becomes clickable. A lot of old folks work at our company.

Thanks for your theme. - junaga

**Comment by tolking** [comment]
check [smooth-scrolling](https://vuepress.vuejs.org/theme/default-theme-config.html#smooth-scrolling)

maybe you need to set it `false`

Then you can write CSS targeting that page only in `.vuepress/styles/index.styl`

```css
::-webkit-scrollbar {
  max-width: 20px !important;
}
```
