### ISSUE TITLE
code textcolor in light mode

### ISSUE THREAD

**Issue by xxholly32** [tolking/vuepress-theme-default-prefers-color-scheme#5]
hi, me agian

there is the problem

![image](https://user-images.githubusercontent.com/6063358/63644248-41957580-c717-11e9-8ebd-ead02e4ef217.png)

i think code mode theme should be the same before, even in the dark mode

**Comment by tolking** [comment]
I haven't encountered this problem yet. Can you show me your config.js file?

I like white.
you can change `palette.styl` -> `$codeBgLightColor` `$preTextLightColor` `$highlightedBgLightColor` `$languageTextLightColor` `$lineNumbersLightColor`

**Comment by xxholly32** [comment]
ok isee ,i was misunderstanding at first, i thought light was defalut theme.

in my opinion, light should as same as vuepress default theme.
